<?php

namespace Kwarcek\ZondacryptoRestApiPhp\Tests\Unit\Public\Requests;

use Kwarcek\ZondacryptoRestApiPhp\Public\Requests\TradingRequest;
use Kwarcek\ZondacryptoRestApiPhp\Tests\Unit\Public\TestCase;

class TradingRequestTest extends TestCase
{
    protected TradingRequest $request;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->request = new TradingRequest($this->client);
    }

    public function test_chuj()
    {
        var_dump($this->request->orderbook());
    }
}