GET https://api.zonda.exchange/rest/trading/ticker
Accept: application/json

###

GET https://api.zonda.exchange/rest/trading/ticker/BTC-PLN
Accept: application/json

###

GET https://api.zonda.exchange/rest/trading/stats
Accept: application/json

###

GET https://api.zonda.exchange/rest/trading/stats/BTC-PLN
Accept: application/json

###

GET https://api.zonda.exchange/rest/trading/orderbook/BTC-PLN
Accept: application/json

###

GET https://api.zonda.exchange/rest/trading/orderbook-limited/BTC-PLN/10
Accept: application/json

###

GET https://api.zonda.exchange/rest/trading/transactions/BTC-PLN
Accept: application/json

###

GET https://api.zonda.exchange/rest/trading/transactions/BTC-PLN?limit=10&fromTime=1673395200&sort=desc
Accept: application/json

###

GET https://api.zonda.exchange/rest/trading/candle/history/BTC-PLN/900?from=1543410329000&to=1543410329000
Accept: application/json