<?php

namespace Kwarcek\ZondacryptoRestApiPhp\Tests\Unit\Private\Requests;

use Kwarcek\ZondacryptoRestApiPhp\Private\Requests\HistoryRequest;
use Kwarcek\ZondacryptoRestApiPhp\Tests\Unit\Private\TestCase;

class HistoryRequestTest extends TestCase
{
    protected HistoryRequest $historyRequest;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->historyRequest = new HistoryRequest($this->client);
    }

    public function test_trading_request_get_ticker()
    {
        $response = $this->historyRequest->getTransactions();

        var_dump($response->getStatusCode());

        $this->assertIsArray($response);
        $this->assertArrayHasKey('code', $response);
        $this->assertArrayHasKey('data', $response);
        $this->assertArrayHasKey('items', $response['data']);
        $this->assertIsArray($response['data']['items']);
    }
}