<?php

namespace Kwarcek\ZondacryptoRestApiPhp\Tests\Unit\Private;

use Kwarcek\ZondacryptoRestApiPhp\Private\AuthCredentials;
use Kwarcek\ZondacryptoRestApiPhp\Private\Client;
use PHPUnit\Framework\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    protected Client $client;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $authCredentials = new AuthCredentials('', '');
        $this->client = new Client($authCredentials);
    }
}